"""
Various constants used to build bazel-diff
"""

RULES_JVM_EXTERNAL_TAG = "6.7"
RULES_JVM_EXTERNAL_SHA = ""
RULES_KOTLIN_VERSION = "2.1.3"
RULES_KOTLIN_SHA = ""
RULES_JAVA_VERSION = "8.11.0"
RULES_JAVA_INTEGRITY = ""
