# @generated by `bazel run //tools/e2e:regen` -- do not edit by hand.
"""Every JUnit e2e case under cli/src/test/kotlin/com/bazel_diff/e2e, one entry each.

//tools/e2e:defs.bzl turns each entry into its own kt_jvm_test target, so a
case's runtime is bounded by its own timeout instead of the whole class's.
Run `make regen-e2e` after adding, renaming or removing a `@Test` method.
"""

KOTLIN_E2E_SUITES = [
    {
        "name": "E2ETest",
        "test_class": "com.bazel_diff.e2e.E2ETest",
        "cases": [
            {
                "name": "testE2E",
                "timeout": "short",
            },
            {
                "name": "testServeEndToEnd",
                "timeout": "short",
            },
            {
                "name": "testServeDoesNotReuseMacroDigestAcrossRevisions",
                "timeout": "short",
            },
            {
                "name": "testDetermineBazelVersion",
                "timeout": "short",
            },
            {
                "name": "testE2EWithNoKeepGoing",
                "timeout": "short",
            },
            {
                "name": "testE2EIncludingTargetType",
                "timeout": "short",
            },
            {
                "name": "testE2EWithTargetType",
                "timeout": "short",
            },
            {
                "name": "testGenerateHashesWithCqueryStreamedProto",
                "timeout": "short",
            },
            {
                "name": "testExcludeTargetsQueryFiltersManualTargets",
                "timeout": "short",
            },
            {
                "name": "testFineGrainedHashExternalRepo",
                "timeout": "short",
            },
            {
                "name": "testFineGrainedHashBzlMod",
                "timeout": "short",
            },
            {
                "name": "testFineGrainedHashBzlModCquery",
                "timeout": "short",
            },
            {
                "name": "testBzlmodTransitiveDepsQuery",
                "timeout": "short",
            },
            {
                "name": "testBzlmodTransitiveDepsCquery",
                "timeout": "short",
            },
            {
                "name": "testBzlmodCCTransitiveDepsQuery",
                "timeout": "short",
            },
            {
                "name": "testUseCqueryWithExternalDependencyChange",
                "timeout": "short",
            },
            {
                "name": "testUseCqueryWithAndroidCodeChange",
                "timeout": "short",
            },
            {
                "name": "testTargetDistanceMetrics",
                "timeout": "short",
            },
            {
                "name": "testCqueryWithFailingAnalysisTargets",
                "timeout": "short",
            },
            {
                "name": "testKeepGoingSilentlyDropsTargetsOnRepoRuleFailure_reproducerForIssue398",
                "timeout": "short",
            },
            {
                "name": "testUndeclaredWorkspaceReadIsNotImpacted_reproducerForIssue401",
                "timeout": "short",
            },
            {
                "name": "testPackageGroupChangeImpactsConsumers_regressionForIssue441",
                "timeout": "short",
            },
            {
                "name": "testBzlmodShowRepoDetectsModuleBazelChanges",
                "timeout": "short",
            },
            {
                "name": "testExcludeExternalTargetsFiltersBzlmodSyntheticLabels",
                "timeout": "short",
            },
            {
                "name": "testModuleBazelCommentOnlyChangeDoesNotImpactTargets_regressionForIssue83",
                "timeout": "short",
            },
            {
                "name": "testGenerateHashesIsHermeticAcrossWorkspacePaths",
                "timeout": "short",
            },
            {
                "name": "testModuleBazelLockReformatDoesNotImpactTargets",
                "timeout": "short",
            },
            {
                "name": "testBzlmodLocalPathOverrideWorks_regressionForIssue196",
                "timeout": "short",
            },
            {
                "name": "testGoModUpdateImpactsGoTargets_regressionForIssue266",
                "timeout": "short",
            },
            {
                "name": "testMacroBzlChangeImpactsCallers_regressionForIssue259And227",
                "timeout": "short",
            },
            {
                "name": "testRemoteProtoVersionBumpImpactsConsumer",
                "timeout": "short",
            },
            {
                "name": "testExternalGoDepsAppearInHashes_regressionForIssue228",
                "timeout": "short",
            },
            {
                "name": "testTransitiveExternalRepoChangeImpactsConsumer_regressionForIssue184",
                "timeout": "short",
            },
            {
                "name": "testWrappedExternalRepoFileChangeImpactsMainConsumer_regressionForIssue197",
                "timeout": "short",
            },
            {
                "name": "testHubSpokeVersionBumpImpactsConsumer_fineGrainedHubPrefixCollision",
                "timeout": "short",
            },
            {
                "name": "testFineGrainedExternalRepoHashesAreHermeticAcrossWorkspacePaths",
                "timeout": "short",
            },
            {
                "name": "testAddingUnrelatedMacroDoesNotImpactExistingTargets_reproducerForIssue365",
                "timeout": "short",
            },
            {
                "name": "testEditingRuleBzlDoesNotOverInvalidateSamePackageTargets",
                "timeout": "short",
            },
            {
                "name": "testEditingCrossFileMacroImpactsConsumerNotSiblings",
                "timeout": "short",
            },
            {
                "name": "testEditingCrossFileRuleImpactsConsumerNotSiblings",
                "timeout": "short",
            },
        ],
    },
]
