# @generated by `bazel run //tools/e2e:regen` -- do not edit by hand.
"""Every libtest e2e case under tests/e2e, one entry each.

//tools/e2e:defs.bzl turns each entry into its own rust_test target that runs
exactly one case, so a case's runtime is bounded by its own timeout instead of
the whole crate's. Run `make regen-e2e` after adding, renaming or removing a
`#[test]` fn.
"""

RUST_E2E_SUITES = [
    {
        "name": "e2e_test",
        "cases": [
            {
                "name": "core::cquery_failing_analysis_targets",
                "timeout": "moderate",
            },
            {
                "name": "core::cquery_streamed_proto",
                "timeout": "moderate",
            },
            {
                "name": "core::exclude_targets_query_filters_manual_targets",
                "timeout": "moderate",
            },
            {
                "name": "core::integration_golden",
                "timeout": "moderate",
            },
            {
                "name": "core::integration_no_keep_going",
                "timeout": "moderate",
            },
            {
                "name": "core::integration_target_types",
                "timeout": "moderate",
            },
            {
                "name": "core::keep_going_partial_graph_behavior",
                "timeout": "moderate",
            },
            {
                "name": "core::serve_end_to_end",
                "timeout": "moderate",
            },
            {
                "name": "core::serve_macro_digest_is_revision_scoped",
                "timeout": "moderate",
            },
            {
                "name": "core::target_distance_metrics",
                "timeout": "moderate",
            },
            {
                "name": "external::bzlmod_cc_transitive_deps_query",
                "timeout": "moderate",
            },
            {
                "name": "external::bzlmod_show_repo_and_external_filtering",
                "timeout": "moderate",
            },
            {
                "name": "external::bzlmod_transitive_deps_cquery",
                "timeout": "moderate",
            },
            {
                "name": "external::bzlmod_transitive_deps_query",
                "timeout": "moderate",
            },
            {
                "name": "external::cquery_android_source_change_platforms",
                "timeout": "moderate",
            },
            {
                "name": "external::cquery_external_dependency_change_platforms",
                "timeout": "moderate",
            },
            {
                "name": "external::fine_grained_bzlmod_repo",
                "timeout": "moderate",
            },
            {
                "name": "external::fine_grained_bzlmod_repo_cquery",
                "timeout": "moderate",
            },
            {
                "name": "external::fine_grained_workspace_external_repo",
                "timeout": "moderate",
            },
            {
                "name": "external::hub_spoke_version_bump_impacts_consumer_behind_fine_grained_hub",
                "timeout": "moderate",
            },
            {
                "name": "external::remote_proto_bump_impacts_consumer",
                "timeout": "moderate",
            },
            {
                "name": "external::transitive_external_repo_change_reaches_consumer",
                "timeout": "moderate",
            },
            {
                "name": "regressions::always_affected_tag_marks_non_hermetic_target",
                "timeout": "moderate",
            },
            {
                "name": "regressions::cross_file_macro_change_is_scoped",
                "timeout": "moderate",
            },
            {
                "name": "regressions::cross_file_rule_change_is_scoped",
                "timeout": "moderate",
            },
            {
                "name": "regressions::external_go_dependencies_appear_in_hashes",
                "timeout": "moderate",
            },
            {
                "name": "regressions::fine_grained_external_hashes_are_hermetic",
                "timeout": "moderate",
            },
            {
                "name": "regressions::go_mod_update_impacts_go_targets",
                "timeout": "moderate",
            },
            {
                "name": "regressions::hashes_are_hermetic_across_workspace_paths",
                "timeout": "moderate",
            },
            {
                "name": "regressions::local_path_override_works_for_query_and_cquery",
                "timeout": "moderate",
            },
            {
                "name": "regressions::macro_bzl_change_impacts_callers",
                "timeout": "moderate",
            },
            {
                "name": "regressions::module_comment_and_lock_reformat_are_noops",
                "timeout": "moderate",
            },
            {
                "name": "regressions::package_group_change_impacts_consumers",
                "timeout": "moderate",
            },
            {
                "name": "regressions::rule_bzl_change_is_scoped_to_consumer",
                "timeout": "moderate",
            },
            {
                "name": "regressions::undeclared_workspace_read_is_not_impacted_without_opt_in",
                "timeout": "moderate",
            },
            {
                "name": "regressions::unrelated_macro_does_not_overinvalidate",
                "timeout": "moderate",
            },
            {
                "name": "regressions::wrapped_external_repo_change_reaches_main_consumer",
                "timeout": "moderate",
            },
            {
                "name": "support::normalizes_rules_jvm_external_canonical_names_across_bazel_versions",
                "timeout": "moderate",
            },
        ],
    },
]
