#!/usr/bin/env python3
"""Regenerates the per-case Bazel test lists that split the e2e suites.

Both e2e suites in this repo are single Bazel targets that run dozens of cases
in one process: `//cli:E2ETest` (JUnit) and `//tests:e2e_test` (libtest). One
target means one timeout, one cache entry and one log for the whole suite, so a
single case's runtime is invisible and a single case's failure re-runs
everything. This tool inverts that: it reads the test sources and emits one
entry per case, which //tools/e2e:defs.bzl expands into its own test target with
its own timeout (300s by default -- see DEFAULT_TIMEOUT).

Nothing about the split is hand-maintained. Add a `@Test` method to any class
under the Kotlin e2e directory, or a `#[test]` fn to any module under the Rust
e2e directory, run `make regen-e2e`, and the new target exists. CI runs
`//tools/e2e:regen_check`, which fails when the checked-in lists no longer match
the sources.

A case that does not fit the default timeout -- or one quick enough to be held
to a tighter one -- declares its own with a marker comment on the lines directly
above it (both languages use `//`, so the spelling is the same):

    // e2e-timeout: long
    @Test
    fun testSomethingSlow() { ... }

Usage:
    python3 tools/e2e/split_e2e_tests.py           # rewrite the generated files
    python3 tools/e2e/split_e2e_tests.py --check   # exit 1 if they are stale
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Sequence

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

#: Every generated target gets this timeout unless the case overrides it. Bazel
#: reads "moderate" as 300 seconds.
#:
#: Not "short" (60s), which is what a case costs on a fast dev machine and
#: nowhere near what it costs anywhere else. Two things stretch a case past 60s
#: even after //tools/e2e:defs.bzl caps how many run at once:
#:
#: - A case run as its own target pays ~7s of fixed setup that an in-process run
#:   amortises across the whole class (testE2E: 10.5s in-suite, 17.3s alone),
#:   and it overlaps with other cases that are each driving a nested Bazel.
#:   Measured on a 28-core Apple Silicon Mac with warm caches, the slowest case
#:   in each suite lands at 130.6s (testFineGrainedHashBzlModCquery) and 126.4s
#:   (external::fine_grained_bzlmod_repo_cquery).
#: - CI is slower than that machine. Its macos-latest x Bazel 8.x cell runs the
#:   JUnit suite in ~1150s against ~460s here, so budget for ~2.5x.
#:
#: testFineGrainedHashBzlModCquery alone settles it: 75s warm, in-process and
#: uncontended, so it cannot fit 60s under any conditions.
#:
#: A case is still free to declare "short" with a marker if it is genuinely
#: quick and worth holding to that bound.
DEFAULT_TIMEOUT = "moderate"

#: Bazel's timeout vocabulary, with the wall-clock bound each one names.
VALID_TIMEOUTS = {
    "short": 60,
    "moderate": 300,
    "long": 900,
    "eternal": 3600,
}

#: Where the Kotlin e2e classes live. Any `*.kt` below this directory is scanned.
KOTLIN_E2E_DIR = "cli/src/test/kotlin/com/bazel_diff/e2e"

#: The Bazel package whose BUILD file declares the Kotlin targets, and the name
#: the un-split suite target keeps.
KOTLIN_GENERATED_BZL = "tools/e2e/kotlin_e2e_cases.bzl"

#: Crate root of the Rust e2e integration test, and the directory holding its
#: modules. `tests/e2e.rs` itself only declares `mod`s; the cases live below.
RUST_CRATE_ROOT = "tests/e2e.rs"
RUST_E2E_DIR = "tests/e2e"
RUST_SUITE_NAME = "e2e_test"
RUST_GENERATED_BZL = "tools/e2e/rust_e2e_cases.bzl"

#: Modules with no `#[test]` of their own (helpers) are still scanned, so this
#: marker is the only thing that decides whether a file contributes cases.
TIMEOUT_MARKER = re.compile(r"^//\s*e2e-timeout:\s*(\S+)\s*$")

GENERATED_HEADER = "# @generated by `bazel run //tools/e2e:regen` -- do not edit by hand."


class GeneratorError(Exception):
    """A malformed test source, or a split that cannot be expressed in Bazel."""


# ---------------------------------------------------------------------------
# Parsed models
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Case:
    """One test case: a JUnit method or a libtest function."""

    #: JUnit method name, or the Rust path (`core::integration_golden`).
    name: str
    timeout: str = DEFAULT_TIMEOUT


@dataclass
class KotlinSuite:
    """One JUnit test class, and the cases it declares."""

    name: str
    test_class: str
    cases: list[Case] = field(default_factory=list)


@dataclass
class RustSuite:
    """The Rust integration test crate, and the cases it declares."""

    name: str
    cases: list[Case] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Shared parsing helpers
# ---------------------------------------------------------------------------


def _timeout_from_preceding_lines(lines: Sequence[str], index: int) -> str:
    """Reads the `// e2e-timeout:` marker attached to the declaration at *index*.

    The marker may sit anywhere in the unbroken run of comment/annotation lines
    directly above the declaration, so it survives being written above or below
    a doc comment or an `@Ignore`. A blank line ends the run: a marker further
    up belongs to whatever came before, not to this case.
    """
    for line in reversed([line.strip() for line in lines[:index]]):
        if not line:
            return DEFAULT_TIMEOUT
        match = TIMEOUT_MARKER.match(line)
        if match:
            timeout = match.group(1)
            if timeout not in VALID_TIMEOUTS:
                raise GeneratorError(
                    "unknown e2e-timeout {!r}; expected one of {}".format(
                        timeout, ", ".join(sorted(VALID_TIMEOUTS))
                    )
                )
            return timeout
        if not (line.startswith("//") or line.startswith("#[") or line.startswith("@")
                or line.startswith("*") or line.startswith("/*")):
            return DEFAULT_TIMEOUT
    return DEFAULT_TIMEOUT


# ---------------------------------------------------------------------------
# Kotlin
# ---------------------------------------------------------------------------

_KOTLIN_PACKAGE = re.compile(r"^package\s+([\w.]+)\s*$")
_KOTLIN_CLASS = re.compile(r"^(?:(?:public|internal|open|abstract|final|sealed)\s+)*class\s+(\w+)")
_KOTLIN_TEST_ANNOTATION = re.compile(r"^@(?:org\.junit\.)?Test\b")
_KOTLIN_FUN = re.compile(r"\bfun\s+`?([\w ]+?)`?\s*\(")


def parse_kotlin_source(text: str, source_path: str) -> list[KotlinSuite]:
    """Extracts every `@Test`-annotated method, grouped by declaring class.

    Deliberately line-based rather than a real Kotlin parse: the only shapes it
    has to recognise are a top-level `class` declaration and a `fun` preceded by
    `@Test`, both of which are unambiguous at column 0 / after an annotation.
    Private helpers are invisible to it precisely because they carry no `@Test`.
    """
    lines = text.splitlines()

    package = ""
    for line in lines:
        match = _KOTLIN_PACKAGE.match(line.strip())
        if match:
            package = match.group(1)
            break
    if not package:
        raise GeneratorError("{}: no package declaration".format(source_path))

    suites: list[KotlinSuite] = []
    current: KotlinSuite | None = None
    pending_test_at: int | None = None

    for index, raw in enumerate(lines):
        stripped = raw.strip()

        # Only column-0 classes are suites; a nested class cannot be a JUnit
        # test_class on its own without an outer-class-qualified name, and this
        # repo has none.
        if not raw[:1].isspace():
            class_match = _KOTLIN_CLASS.match(stripped)
            if class_match:
                current = KotlinSuite(
                    name=class_match.group(1),
                    test_class="{}.{}".format(package, class_match.group(1)),
                )
                suites.append(current)
                pending_test_at = None
                continue

        if _KOTLIN_TEST_ANNOTATION.match(stripped):
            pending_test_at = index
            continue

        if pending_test_at is None:
            continue

        fun_match = _KOTLIN_FUN.search(stripped)
        if not fun_match:
            continue

        method = fun_match.group(1)
        if current is None:
            raise GeneratorError(
                "{}: @Test fun {} is not inside a top-level class".format(source_path, method)
            )
        if " " in method:
            # Backtick-quoted names cannot round-trip through a Bazel target
            # name, and a JUnit filter regex would need escaping too.
            raise GeneratorError(
                "{}: @Test fun `{}` has spaces in its name; the split needs a plain "
                "identifier so it can name a Bazel target after it".format(source_path, method)
            )
        current.cases.append(
            Case(name=method, timeout=_timeout_from_preceding_lines(lines, pending_test_at))
        )
        pending_test_at = None

    return [suite for suite in suites if suite.cases]


# ---------------------------------------------------------------------------
# Rust
# ---------------------------------------------------------------------------

_RUST_TEST_ATTRIBUTE = re.compile(r"^#\[test\]$")
_RUST_FN = re.compile(r"^(?:pub\s+)?(?:async\s+)?fn\s+(\w+)")
_RUST_MOD_BLOCK = re.compile(r"^(?:pub(?:\([\w:]+\))?\s+)?mod\s+(\w+)\s*\{")
_RUST_MOD_DECL = re.compile(r"^(?:pub(?:\([\w:]+\))?\s+)?mod\s+(\w+)\s*;")
_RUST_LINE_COMMENT = re.compile(r"//.*$")
_RUST_LITERAL = re.compile(r"r#*\"[^\"]*\"#*|\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])'")


def _strip_rust_literals(line: str) -> str:
    """Blanks out string/char literals and line comments on a single line.

    Only the brace counting below needs this, and only so a `{` inside a string
    or a comment cannot desync the inline-`mod` nesting. Deliberately per-line
    and therefore approximate: a raw string spanning several lines would still
    confuse it, and nothing under the e2e directory has one.
    """
    return _RUST_LINE_COMMENT.sub("", _RUST_LITERAL.sub("", line))


def rust_module_prefix(rel_path: str) -> str:
    """Maps a source path under the e2e directory to its crate module path.

    `tests/e2e/core.rs` is reachable as `core` because `tests/e2e.rs` declares it
    with `#[path]`; `tests/e2e/support/mod.rs` is `support`, and a file inside
    that directory would be `support::<stem>`.
    """
    relative = rel_path[len(RUST_E2E_DIR) + 1 :] if rel_path.startswith(RUST_E2E_DIR + "/") else rel_path
    parts = relative[: -len(".rs")].split("/")
    if parts[-1] == "mod":
        parts.pop()
    return "::".join(parts)


def parse_rust_source(text: str, module_prefix: str) -> list[Case]:
    """Extracts every `#[test]` fn, qualified by its inline `mod` nesting.

    Brace counting is enough to track `mod foo { ... }` blocks because the only
    thing it has to get right is which module a `fn` at a given point belongs
    to; string and comment contents that contain braces would have to also look
    like a `mod` header to matter.
    """
    lines = text.splitlines()
    cases: list[Case] = []
    module_stack: list[str] = []
    brace_stack: list[int] = []
    depth = 0
    pending_test_at: int | None = None

    for index, raw in enumerate(lines):
        code = _strip_rust_literals(raw)
        stripped = code.strip()

        if _RUST_TEST_ATTRIBUTE.match(stripped):
            pending_test_at = index
        elif pending_test_at is not None:
            fn_match = _RUST_FN.match(stripped)
            if fn_match:
                path = "::".join(
                    part for part in [module_prefix, *module_stack, fn_match.group(1)] if part
                )
                cases.append(
                    Case(name=path, timeout=_timeout_from_preceding_lines(lines, pending_test_at))
                )
                pending_test_at = None

        mod_match = _RUST_MOD_BLOCK.match(stripped)
        if mod_match:
            module_stack.append(mod_match.group(1))
            brace_stack.append(depth)

        depth += code.count("{") - code.count("}")

        while brace_stack and depth <= brace_stack[-1]:
            brace_stack.pop()
            module_stack.pop()

    return cases


def rust_declared_modules(crate_root_text: str) -> set[str]:
    """The top-level modules `tests/e2e.rs` declares."""
    return {
        match.group(1)
        for match in (_RUST_MOD_DECL.match(line.strip()) for line in crate_root_text.splitlines())
        if match
    }


# ---------------------------------------------------------------------------
# Target names
# ---------------------------------------------------------------------------


def kotlin_target_name(suite: KotlinSuite, case: Case) -> str:
    return "{}_{}".format(suite.name, case.name)


def rust_target_name(suite_name: str, case: Case) -> str:
    return "{}_{}".format(suite_name, case.name.replace("::", "_"))


def _assert_unique_targets(names: Iterable[str]) -> None:
    seen: set[str] = set()
    for name in names:
        if name in seen:
            raise GeneratorError(
                "two e2e cases both want the Bazel target name {!r}; rename one of "
                "them so each case gets its own target".format(name)
            )
        seen.add(name)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render_cases(cases: Sequence[Case], indent: str) -> list[str]:
    out: list[str] = []
    for case in cases:
        out.append('{}{{'.format(indent))
        out.append('{}    "name": "{}",'.format(indent, case.name))
        out.append('{}    "timeout": "{}",'.format(indent, case.timeout))
        out.append('{}}},'.format(indent))
    return out


def render_kotlin_bzl(suites: Sequence[KotlinSuite]) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Every JUnit e2e case under {}, one entry each.'.format(KOTLIN_E2E_DIR),
        "",
        "//tools/e2e:defs.bzl turns each entry into its own kt_jvm_test target, so a",
        "case's runtime is bounded by its own timeout instead of the whole class's.",
        'Run `make regen-e2e` after adding, renaming or removing a `@Test` method.',
        '"""',
        "",
        "KOTLIN_E2E_SUITES = [",
    ]
    for suite in suites:
        lines.append("    {")
        lines.append('        "name": "{}",'.format(suite.name))
        lines.append('        "test_class": "{}",'.format(suite.test_class))
        lines.append('        "cases": [')
        lines.extend(_render_cases(suite.cases, "            "))
        lines.append("        ],")
        lines.append("    },")
    lines.append("]")
    return "\n".join(lines) + "\n"


def render_rust_bzl(suites: Sequence[RustSuite]) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Every libtest e2e case under {}, one entry each.'.format(RUST_E2E_DIR),
        "",
        "//tools/e2e:defs.bzl turns each entry into its own rust_test target that runs",
        "exactly one case, so a case's runtime is bounded by its own timeout instead of",
        'the whole crate\'s. Run `make regen-e2e` after adding, renaming or removing a',
        "`#[test]` fn.",
        '"""',
        "",
        "RUST_E2E_SUITES = [",
    ]
    for suite in suites:
        lines.append("    {")
        lines.append('        "name": "{}",'.format(suite.name))
        lines.append('        "cases": [')
        lines.extend(_render_cases(suite.cases, "            "))
        lines.append("        ],")
        lines.append("    },")
    lines.append("]")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Collection
# ---------------------------------------------------------------------------


def collect_kotlin_suites(repo_root: Path) -> list[KotlinSuite]:
    directory = repo_root / KOTLIN_E2E_DIR
    if not directory.is_dir():
        raise GeneratorError("{} does not exist".format(KOTLIN_E2E_DIR))

    suites: list[KotlinSuite] = []
    for path in sorted(directory.rglob("*.kt")):
        rel = path.relative_to(repo_root).as_posix()
        suites.extend(parse_kotlin_source(path.read_text(encoding="utf-8"), rel))

    suites.sort(key=lambda suite: suite.name)
    # The suite's own test_suite and its `_all` escape hatch share the namespace
    # with the per-case targets, so they belong in the uniqueness check: a
    # `@Test fun all()` would otherwise silently redefine `<Suite>_all`.
    _assert_unique_targets(
        [suite.name for suite in suites]
        + ["{}_all".format(suite.name) for suite in suites]
        + [kotlin_target_name(suite, case) for suite in suites for case in suite.cases]
    )
    return suites


def collect_rust_suites(repo_root: Path) -> list[RustSuite]:
    directory = repo_root / RUST_E2E_DIR
    if not directory.is_dir():
        raise GeneratorError("{} does not exist".format(RUST_E2E_DIR))

    declared = rust_declared_modules((repo_root / RUST_CRATE_ROOT).read_text(encoding="utf-8"))

    cases: list[Case] = []
    for path in sorted(directory.rglob("*.rs")):
        rel = path.relative_to(repo_root).as_posix()
        prefix = rust_module_prefix(rel)
        found = parse_rust_source(path.read_text(encoding="utf-8"), prefix)
        if not found:
            continue
        root_module = prefix.split("::")[0]
        if root_module not in declared:
            raise GeneratorError(
                "{} declares #[test] fns but `mod {};` is missing from {}, so the crate "
                "never compiles them".format(rel, root_module, RUST_CRATE_ROOT)
            )
        cases.extend(found)

    cases.sort(key=lambda case: case.name)
    _assert_unique_targets(
        [RUST_SUITE_NAME, "{}_all".format(RUST_SUITE_NAME)]
        + [rust_target_name(RUST_SUITE_NAME, case) for case in cases]
    )
    return [RustSuite(name=RUST_SUITE_NAME, cases=cases)]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def find_repo_root() -> Path:
    """Locates the workspace root under `bazel run`, `bazel test` and plain python."""
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if workspace:
        return Path(workspace)

    srcdir = os.environ.get("TEST_SRCDIR")
    test_workspace = os.environ.get("TEST_WORKSPACE")
    if srcdir and test_workspace:
        return Path(srcdir) / test_workspace

    for candidate in [Path(__file__).resolve(), *Path(__file__).resolve().parents]:
        if (candidate / "MODULE.bazel").is_file():
            return candidate
    raise GeneratorError("cannot locate the repository root")


def generate(repo_root: Path) -> dict[str, str]:
    """Renders every generated file, keyed by its repo-relative path."""
    return {
        KOTLIN_GENERATED_BZL: render_kotlin_bzl(collect_kotlin_suites(repo_root)),
        RUST_GENERATED_BZL: render_rust_bzl(collect_rust_suites(repo_root)),
    }


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if a generated file is out of date",
    )
    args = parser.parse_args(argv)

    repo_root = find_repo_root()
    generated = generate(repo_root)

    if not args.check:
        for rel_path, content in generated.items():
            (repo_root / rel_path).write_text(content, encoding="utf-8")
            print("wrote {}".format(rel_path))
        return 0

    stale = []
    for rel_path, content in generated.items():
        path = repo_root / rel_path
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != content:
            stale.append(rel_path)

    if stale:
        print(
            "The e2e test split is out of date:\n"
            + "".join("  {}\n".format(path) for path in stale)
            + "\nAn e2e test was added, renamed or removed without regenerating the\n"
            "per-case Bazel targets. Run:\n\n    make regen-e2e\n\n"
            "and commit the result.",
            file=sys.stderr,
        )
        return 1

    print("e2e test split is up to date ({} files checked)".format(len(generated)))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except GeneratorError as error:
        print("error: {}".format(error), file=sys.stderr)
        sys.exit(2)
