package com.bazel_diff.cli

import assertk.assertThat
import assertk.assertions.hasSize
import assertk.assertions.isEqualTo
import assertk.assertions.isNotEmpty
import java.io.ByteArrayInputStream
import java.io.InputStream
import org.junit.Assert.assertThrows
import org.junit.Test

class VersionProviderTest {
  @Test
  fun loadsBundledVersionResource() {
    // tools/version is generated by the //cli:version_file genrule and packaged as a
    // classpath resource at `cli/version`. This test exercises the happy path: the
    // resource is present, the BufferedReader reads it, and the trimmed contents come
    // back as the single-element version array picocli expects.
    val versions = VersionProvider().getVersion()
    assertThat(versions).hasSize(1)
    assertThat(versions[0]).isNotEmpty()
  }

  @Test
  fun missingResourceThrows() {
    val emptyLoader =
        object : ClassLoader() {
          override fun getResourceAsStream(name: String): InputStream? = null
        }
    assertThrows(IllegalArgumentException::class.java) {
      VersionProvider(emptyLoader).getVersion()
    }
  }

  @Test
  fun fallsBackToVersionResourceWhenCliVersionAbsent() {
    val loader =
        object : ClassLoader() {
          override fun getResourceAsStream(name: String): InputStream? =
              when (name) {
                "cli/version" -> null
                "version" -> ByteArrayInputStream("1.2.3-fallback\n".toByteArray())
                else -> null
              }
        }
    assertThat(VersionProvider(loader).getVersion().toList()).isEqualTo(listOf("1.2.3-fallback"))
  }
}
