package com.bazel_diff.cli

import assertk.assertThat
import assertk.assertions.hasSize
import assertk.assertions.isNotEmpty
import org.junit.Test

class VersionProviderTest {
  @Test
  fun loadsBundledVersionResource() {
    // tools/version is generated by the //cli:version_file genrule and packaged as a
    // classpath resource at `cli/version`. This test exercises the happy path: the
    // resource is present, the BufferedReader reads it, and the trimmed contents come
    // back as the single-element version array picocli expects.
    val versions = VersionProvider().getVersion()
    assertThat(versions).hasSize(1)
    assertThat(versions[0]).isNotEmpty()
  }
}
