# Publish new releases to Bazel Central Registry.
name: Publish to BCR
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: git tag being released
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.0.0
    with:
      tag_name: ${{ inputs.tag_name }}
      # GitHub repository which is a fork of the upstream where the Pull Request will be opened.
      registry_fork: maxwellE/bazel-central-registry
      attest: false
      author_name: Maxwell Elliott
      author_email: maxwell@elliott.now
      committer_name: Maxwell Elliott
      committer_email: maxwell@elliott.now
    permissions:
      contents: write
    secrets:
      # Necessary to push to the BCR fork, and to open a pull request against a registry
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
